# Make sure you podman login to the Red Hat registry, then:
# ansible-builder build -t trusted-tox-ee:latest
# To host locally:
# * run the docker registry:
#     podman run -d -p 5000:5000 --name registry registry:latest
# * Add the docker registry as an insecure registry:
#     vi /etc/containers/registries.conf.d/099-localhost-registry.conf
#     
#       [[registry]]
#       location = "localhost:5000"
#       insecure = true
#
# * Tag the built image:
#     podman image tag localhost/trusted-tox-ee localhost:5000/trusted-tox-ee
# * Push the image:
#     podman push localhost:5000/trusted-tox-ee
# * Verify the image is there:
#     curl -X GET http://localhost:5000/v2/_catalog

version: 3

images:
  base_image:
    name: "registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel9:latest"

dependencies:
  system:
    - pip
  #system:
  #  - python3-devel
  #  - systemd-devel

      #  python_interpreter:
      # python_path: /usr/bin/python3.11

  python:
    - tox-ansible
    
additional_build_files:
  - src: files/tox-ansible.ini
    dest: configs

additional_build_steps:
  prepend_base:
    - COPY _build/configs/tox-ansible.ini /tmp/tox-ansible.ini

options:
  package_manager_path: /usr/bin/microdnf
