# Make sure you podman login to the Red Hat registry, then:
# ansible-builder build -t trusted-sign-ee:latest
# To host locally:
# * run the docker registry:
#     podman run -d -p 5000:5000 --name registry registry:latest
# * Add the docker registry as an insecure registry:
#     vi /etc/containers/registries.conf.d/099-localhost-registry.conf
#     
#       [[registry]]
#       location = "localhost:5000"
#       insecure = true
#
# * Tag the built image:
#     podman image tag localhost/trusted-sign-ee localhost:5000/trusted-sign-ee
# * Push the image:
#     podman push localhost:5000/trusted-sign-ee
# * Verify the image is there:
#     curl -X GET http://localhost:5000/v2/_catalog

version: 3

images:
  base_image:
    name: "registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel9:latest"

dependencies:
  system:
    - pip

  python:
    - ansible-sign
    
options:
  package_manager_path: /usr/bin/microdnf
